### ISSUE TITLE
Empty lines are ignored by dlog, dslog, and drlog

### ISSUE THREAD

**Issue by schultetwin1** [aperezdc/dmon#12]
This might be by design but wanted to bring this up. After #10 is fixed, empty lines will still not be logged. This is due to logic in dlog, dslog, and drlog to skip empty lines.

From my perspective, if someone wanted to log an empty line, I'd vote to have that empty line show up in the log but would love your perspective on this.

**Comment by aperezdc** [comment]
I think there is value in having an option to ignore empty input lines (so they don't appear in the logs), and as a matter of fact, the [logger(1)](https://man7.org/linux/man-pages/man1/logger.1.html) implementation included with systemd has a `--skip-empty`/`-e` command line option. I have added such an option in commit 9e5aad64d4c300b333e4bcb0292e36e0851af42f :wink:
